modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
modId="brewinandchewin"
version="1.19-2.0"
displayName="Farmer's Respite"
# updateJSONURL=""
logoFile="logo.png"
logoBlur=false
credits="Umpaz, Probleyes, SoyTutta"
authors="Umpaz, Probleyes"
description="An addon for the Farmer's Delight mod centered around brewing tea and coffee in the kettle"
itemIcon="farmersrespite:kettle"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.brewinandchewin]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.brewinandchewin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.brewinandchewin]]
modId="farmersdelight"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
